[project]
name = "python-tachymetre"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Selrrak", email = "chbou602@ulaval.ca" }
]
requires-python = ">=3.14"
dependencies = [
	"serial",
	"pyserial",
	"dataclasses",
	"pyside6>=6.11.2",
]

[project.scripts]
python-tachymetre = "python_tachymetre:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
